config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end

  namespace :api, default: {format: :json} do
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show, :create] do
        resources :comments, only: [:index, :create]
      end
    end
    post 'login', to: 'authentication#login'
    post 'signup', to: 'authentication#create'
  end
  # Defines the root path route ("/")
  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  after_save :update_author_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :text, presence: true
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_author_posts_counter
    author.update(posts_counter: author.posts.length)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    render json: @posts
  end

  def show
    @user_id = params[:user_id]
    @post_id = params[:id]
    @post = Post.find(params[:id])
    render json: @post
  end

  def create
    @current_user = User.find(params[:user_id])
    post = Post.new(title: post_params[:title], text: post_params[:text], author_id: @current_user.id,
                    comments_counter: 0, likes_counter: 0)
    if post.valid?
      post.save
      respond_to do |format|
        msg = { status: 'ok', message: 'Success!' }
        format.json { render json: msg } # don't do msg.to_json
      end
    else
      respond_to do |format|
        msg = { status: 'fail', message: 'Failed!' }
        format.json { render json: msg } # don't do msg.to_json
      end
    end
  end

  private

  def post_params
    params.require(:blog_post).permit(:title, :text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @current_user = current_user
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @current_user = current_user
    @user_id = params[:user_id]
    @post_id = params[:id]
    @post = Post.find(params[:id])
  end

  def new
    @current_user = current_user
    @post = Post.new
  end

  def create
    @current_user = current_user
    post = Post.new(post_params.merge(author_id: @current_user.id, comments_counter: 0, likes_counter: 0))
    if post.valid?
      post.save
      redirect_to user_path(@current_user.id), success: 'Post published'
    else
      redirect_to new_user_post_path(@current_user.id), alert: post.errors.full_messages
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="flex flex-col gap-5">
  <%= render partial: "shared/user_info", locals: { user: @user } %>

  <ul class="flex flex-col gap-5 my-5">
    <% @posts.each do |post| %>
      <li>
        <a href=<%= "/users/#{@user.id}/posts/#{post.id}" %> class="block border p-3 flex flex-col gap-2">
          <h3 class="text-xl"><%= post.title %></h3>
          <p><%= post.text %></p>
          <p class="text-sm self-end"><%= "Comments: #{post.comments_counter || 0}, Likes: #{post.likes_counter || 0 }" %></p>
          <div class="flex flex-col gap-2">
            <% post.recent_comments.each do |comment| %>
              <p><%= "#{comment.author.name}: #{comment.text}" %></p>
            <% end %>
          </div>
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<% flash.each do |type, msg| %>
  <div class="p-3 my-3 border rounded-xl bg-red-300 gap-3">
    <h2 class="font-bold"><%= type.to_upper %></h2>
    <% msg.each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
<% end %>

<%= form_with model: @post, url: user_posts_path do |f| %>
  <div class="border p-3 flex flex-col gap-3">
    <h1 class="text-3xl">Create a new post</h1>
    <div>
      <%= f.label :title, "Title" %>
      <%= f.text_field :title, class: "w-full p-2 border" %>
    </div>
    <div>
      <%= f.label :text, "Body" %>
      <%= f.text_area :text, class: "w-full p-2 border" %>
    </div>
    <%= f.submit "Publish", class: "self-center py-2 px-3 border rounded-xl" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<article class="border p-3 gap-3">
  <div class="flex flex-col justify-between">
    <h1 class="text-2xl"><%= @post.title %></h1>
    <p class="self-end"><%= "Author: #{@post.author.name}" %></p>
    <p class="self-end"><%= "Comments: #{@post.comments_counter || 0}, Likes: #{@post.likes_counter || 0 }" %></p>
  </div>
  <p><%= @post.text %></p>
</article>

<div class="border p-3 mt-3">
  <h3 class="text-md">Comments</h3> 
  <div class="flex flex-col border p-3 gap-2 mt-3">
    <% @post.comments.each do |comment| %>
      <p><%= "#{comment.author.name}: #{comment.text}" %></p>
    <% end %>
  </div>
</div>

<% flash.each do |type, msg| %>
  <div class="p-3 mt-3 border rounded-xl bg-red-500 text-white-">
    <%= type.capitalize %>: <%= msg %>
  </div>
<% end %>

<div class="flex border p-3 gap-2 mt-3">
  <%= button_to user_post_likes_path(@user_id, @post_id), method: :post, class: "self-center py-2 px-3 border rounded-xl" do %>
    Like
  <% end %>

  <%= link_to new_user_post_comment_path(@user_id, @post_id), class: "self-center py-2 px-3 border rounded-xl" do %>
    Post a comment
  <% end %>
</div>  