config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:create]
    end
  end

  namespace :api, default: {format: :json} do
    resources :users, only: [:index, :show] do
      resources :posts, only: [:index, :show, :create] do
        resources :comments, only: [:index, :create]
      end
    end
    post 'login', to: 'authentication#login'
    post 'signup', to: 'authentication#create'
  end
  # Defines the root path route ("/")
  root "users#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="p-5 bg-slate-300">
      <div class="flex justify-between max-w-screen-lg mx-auto">
        <%= link_to root_path, class: "text-3xl" do %>
          Blog App
        <% end %>
        <nav class="flex items-center gap-3">
          <% if user_signed_in? %>
            <%= link_to "New Post", new_user_post_path(@current_user.id) %>
            <%= link_to "Profile", edit_user_registration_path %>
            <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Log in", new_user_session_path %>
            <%= link_to "Sign up", new_user_registration_path %>
          <% end %>
        </nav>
      </div>
    </header>
    <main class="mx-auto max-w-screen-md my-28 px-5 flex flex-col gap-5">
      <% if notice %>
        <p class="notice px-5 py-3 border rounded-xl bg-green-100"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert px-5 py-3 border rounded-xl bg-red-100"><%= alert %></p>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>